name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-latest, macOS, windows-latest]
    env:
      ENDPOINT: ${{ secrets.ENDPOINT }}
      USER: ${{ secrets.USER }}
      SCHEME: ${{ secrets.SCHEME }}
      VERSION: ${{ secrets.VERSION }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SCHAIN_OWNER_PK: ${{ secrets.SCHAIN_OWNER_PK }}
      PRIVATEKEY: ${{ secrets.PRIVATEKEY }}
      FOREIGN_PRIVATEKEY: ${{ secrets.FOREIGN_PRIVATEKEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: skalenetwork/filestorage
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: develop
        path: filestorage
    - name: Copy config
      run:
        cp filestorage/test/utils/config.json test/utils
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        npm i
    - name: Generating test file
      if: matrix.os != 'windows-latest'
      run: npm run generate
    - name: Generating test file on windows
      if: matrix.os == 'windows-latest'
      run: npm run generate-win
    - name: Unit testing
      run: |
        PORT=$(bash run_test_container.sh)
        SKALE_ENDPOINT=$SCHEME$ENDPOINT:$PORT npm test
    - name: Package testing
      run: |
        npm link; npm link @skalenetwork/filestorage.js
        npm run test test/package
    - name: Codecov
      run: |
        npm run coverage

# Fix browser testing
