name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-latest, macOS, windows-latest]
        include:
        - node: 10
          os: ubuntu-latest
          PRIVATEKEY: UBUNTU_10_PK
          FOREIGN_PRIVATEKEY: UBUNTU_10_FPK
        - node: 12
          os: ubuntu-latest
          PRIVATEKEY: UBUNTU_12_PK
          FOREIGN_PRIVATEKEY: UBUNTU_12_FPK
        - node: 10
          os: macOS
          PRIVATEKEY: MAC_10_PK
          FOREIGN_PRIVATEKEY: MAC_10_FPK
        - node: 12
          os: macOS
          PRIVATEKEY: MAC_12_PK
          FOREIGN_PRIVATEKEY: MAC_12_FPK
        - node: 10
          os: windows-latest
          PRIVATEKEY: WIN_10_PK
          FOREIGN_PRIVATEKEY: WIN_10_FPK
        exclude:
        - node: 12
          os: windows-latest
    env:
      SKALE_ENDPOINT: ${{ secrets.SKALE_ENDPOINT }}
      SCHAIN_OWNER_PK: ${{ secrets.SCHAIN_OWNER_PK }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        npm i
    - name: Generating test file
      if: matrix.os != 'windows-latest'
      run: npm run generate
    - name: Generating test file on windows
      if: matrix.os == 'windows-latest'
      run: npm run generate-win
    - name: Unit testing
      env:
        PRIVATEKEY: ${{ secrets[matrix.PRIVATEKEY] }}
        FOREIGN_PRIVATEKEY: ${{ secrets[matrix.FOREIGN_PRIVATEKEY] }}
      run: |
        npm test
    - name: Package testing
      run: |
        npm link; npm link @skalenetwork/filestorage.js
        npm run test test/package
    - name: Codecov
      run: |
        npm run coverage

  browser-test:
    runs-on: ubuntu-latest
    env:
      PRIVATEKEY: ${{ secrets.BROWSER_PK}}
      SKALE_ENDPOINT: ${{ secrets.SKALE_ENDPOINT }}
      SCHAIN_OWNER_PK: ${{ secrets.SCHAIN_OWNER_PK }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      run: |
        npm i
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - name: Chrome testing
      run: |
        npm run test test/browser 
