name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
        include:
        - node: 10
          PRIVATEKEY: UBUNTU_10_PK
          FOREIGN_PRIVATEKEY: UBUNTU_10_FPK
        - node: 12
          PRIVATEKEY: UBUNTU_12_PK
          FOREIGN_PRIVATEKEY: UBUNTU_12_FPK
    env:
      SKALE_ENDPOINT: ${{ secrets.SKALE_ENDPOINT }}
      SCHAIN_OWNER_PK: ${{ secrets.SCHAIN_OWNER_PK }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up environments
      env:
        PRIVATEKEY: ${{ secrets.${{ matrix.env.PRIVATEKEY }} }}
        FOREIGN_PRIVATEKEY: ${{ secrets.${{ matrix.env.FOREIGN_PRIVATEKEY }} }}
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        npm i
    - name: Unit testing
      run: |
        npm test
    - name: Package testing
      run: |
        npm link; npm link @skalenetwork/filestorage.js
        npm run test test/package
