name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
        include:
        - node: 10
          PRIVATEKEY: ${{ matrix.secrets.UBUNTU_10_PK }}
          FOREIGN_PRIVATEKEY: ${{ matrix.secrets.UBUNTU_10_FPK }}
        - node: 12
          PRIVATEKEY: ${{ matrix.secrets.UBUNTU_12_PK }}
          FOREIGN_PRIVATEKEY: ${{ matrix.secrets.UBUNTU_12_FPK }}
    env:
      SKALE_ENDPOINT: ${{ matrix.secrets.SKALE_ENDPOINT}}
      SCHAIN_OWNER_PK: ${{ matrix.secrets.SCHAIN_OWNER_PK }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        npm i
    - name: Unit testing
      run: |
        npm test
    - name: Package testing
      run: |
        npm link; npm link @skalenetwork/filestorage.js
        npm run test test/package
