name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-latest]
        include:
        - node: 10
          os: ubuntu-latest
          PRIVATEKEY: UBUNTU_10_PK
          FOREIGN_PRIVATEKEY: UBUNTU_10_FPK
        - node: 12
          PRIVATEKEY: UBUNTU_12_PK
          FOREIGN_PRIVATEKEY: UBUNTU_12_FPK
    env:
      SKALE_ENDPOINT: ${{ secrets.SKALE_ENDPOINT }}
      SCHAIN_OWNER_PK: ${{ secrets.SCHAIN_OWNER_PK }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        npm i
    - name: Generating test file
      if: matrix.os != 'windows'
      run: npm run generate
    - name: Generating test file on windows
      if: matrix.os == 'windows'
      run: npm run generate-win
    - name: Unit testing
      env:
        PRIVATEKEY: ${{ secrets[matrix.PRIVATEKEY] }}
        FOREIGN_PRIVATEKEY: ${{ secrets[matrix.FOREIGN_PRIVATEKEY] }}
      run: |
        npm test
    - name: Package testing
      run: |
        npm link; npm link @skalenetwork/filestorage.js
        npm run test test/package
