name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    env:
      PRIVATEKEY: ${{ secrets.UBUNTU_10_PK }}
      FOREIGN_PRIVATE_KEY: ${{ secrets.UBUNTU_10_FPK }}
      SKALE_ENDPOINT: ${{ secrets.SKALE_ENDPOINT}}
      SCHAIN_OWNER_PK: ${{ secrets.SCHAIN_OWNER_PK }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        npm i
    - name: Unit testing
      run: |
        npm test
    - name: Package testing
      run: |
        npm link; npm link @skalenetwork/filestorage.js
        npm run test test/package
